### PR TITLE
Support wfresh parameter

### PR DESCRIPTION
**Pull request by 616b2f**

### CODE REVIEW

**Comment by RemcoBlok** [comment]
Hi, thank you very much for your efforts. I did some testing. I used the sample client and server in this repo and added a button to the Secured view that would force another login by passing the wfresh=0 parameter. I found one issue in the WsfederationController where after filling in the username and password on the login form the credentials would be validated again with wfresh=0 requiring an immediate signin again and you would never be redirected back to the relying party. I managed to fix this as follows:


    if (result.SignInRequired)
    {
        var returnUrl = Url.Action("Index");
        var query = Request.Query.Where(q => !q.Key.Equals("wfresh", StringComparison.OrdinalIgnoreCase));
        returnUrl = returnUrl.AddQueryString(QueryString.Create(query).Value);
                
        var loginUrl = Request.PathBase + _options.UserInteraction.LoginUrl;
        var url = loginUrl.AddQueryString(_options.UserInteraction.LoginReturnUrlParameter, returnUrl);

        return Redirect(url);
    }

After this the wfresh worked with the sample in this repo. I also tested it with IdentityServer as a claims provider in ADFS 2016 and wfresh worked there too. 

What did not seem to work with ADFS 2016 is signout. As mentioned here https://github.com/IdentityServer/IdentityServer4.WsFederation/issues/9 support for signout could be added as follows

        private async Task<IActionResult> ProcessSignOut(WsFederationMessage signout)
        {
            var hint = await _tools.IssueJwtAsync(3600, new List<Claim> { new Claim(JwtClaimTypes.Audience, signout.Wtrealm) }); 
            var url = Url.Action("endsession", "connect", new { id_token_hint = hint });
            return Redirect(url);
        }

This solution works with the sample client and server in this repo, but not with IdentityServer as a claims provider in ADFS 2016. ADFS 2016 does not pass the wtrealm parameter to the claims provider on signout. I went back to my IdentityServer 3 claims provider with IdenityServer3.Wsfederation and here signout worked ok without getting the wtrealm parameter passed in by ADFS 2016. So why would IdentityServer 4 need it for a successful signout?

**Comment by 616b2f** [comment]
Sorry for late response. Thank you for your feedback. I need to look in those two issues more closely. The first I am not sure how this would work if we sign the auth requests, if it will still work to remove the wfresh parameter, but for now I think it should do the thing.

For the second, what are you mean by sign out doesn't work? You mean your aren't logged out automatically and afterwords redirected to ADFS afterwords?

**Comment by RemcoBlok** [comment]
For the signout issue I mean that ADFS redirects to WsFederation?wa=wsignout1.0, not WsFederation?wtrealm=urn%3Aaspnetcorerp&wa=wsignout1.0. With the ProcessSignout code I have above you then simply get an error in the WsFederationController.ProcessSignout method saying that the Audience claim cannot have a null value. De Audience claim is used for the login hint. I did ask for help here https://github.com/IdentityServer/IdentityServer4.WsFederation/issues/17, but nothing yet

**Comment by 616b2f** [comment]
I understand now, but signout without any requester information is tricky, because as IDP you don't know where to redirect without wtrealm parameter and you need to validate wreply if it is provided, to prevent redirect to malicious sites.

Any advise where to find a howto on ADFS configuration, I would like to setup an test environment to debug this use case that you are mentioning.

**Pull request merged**
